on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            (JSON.stringify(context, null, 2))
            github.rest.actions.getPendingDeploymentsForRun({
              owner: "sika-example-user",
              repo: "gs-1",
              run_id: ${{github.run_id}},
            }).then(response => {
              console.log(response)
            })

