on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context, null, 2))
            # github.rest.issues.createComment({
            #   issue_number: context.issue.number,
            #   owner: context.repo.owner,
            #   repo: context.repo.repo,
            #   body: '👋 Thanks @'+context.payload.sender.login+' for reporting! \n```\n'+JSON.stringify(context, null, 2)+'\n```\n'
            # })
            github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "main",
              payload: '{ "deploy": "migrate" }',
              description: 'Deploy request from hubot',
              production_environment: true,
            }).then(response => {
              github.rest.repos.createDeploymentStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: response.data.id,
                state: "success",
                comment: "Yesss",
                log_url: "https://google.com",
              })
            })
