on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - uses: actions/checkout@v1
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: http://my-app-url.com
          environment: production
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createDeploymentStatus({
              owner: "sika-example-user",
              repo: "gs-1",
              deployment_id: "${{steps.deployment.outputs.deployment_id}}",
              state: "success",
              comment: "Yesss",
              log_url: "https://google.com",
            })
            github.rest.actions.getPendingDeploymentsForRun({
              owner: "sika-example-user",
              repo: "gs-1",
              run_id: ${{github.run_id}},
            }).then(response => {
              console.log(response)
            })
