on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context, null, 2))
            github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.after,
              payload: '{ "deploy": "migrate" }',
              description: 'Deploy request from hubot',
              production_environment: true,
            })

