on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'main',
              payload: '{ "deploy": "migrate" }',
              description: 'Deploy request from hubot',
              production_environment: true,
            }).then(response => {
              github.rest.repos.createDeploymentStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: response.data.id,
                state: "success",
                comment: "Yesss",
                log_url: "https://google.com",
              })
            })
