on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            let deployment = await github.rest.repos.createDeployment({
              owner: "sika-example-user",
              repo: "gs-1",
              ref: "main",
              payload: '{ "deploy": "migrate" }',
              description: 'Deploy request from hubot',
              production_environment: true,
              required_contexts: [],
            github.rest.repos.createDeploymentStatus({
              owner: "sika-example-user",
              repo: "gs-1",
              deployment_id: deployment.data.id,
              state: "success",
              comment: "Yesss",
              log_url: "https://sika.io",
            })
