name: Deploy pull request

on:
  pull_request:


jobs:
  deploy:
    runs-on: ubuntu-latest

    # permissions: write-all
    permissions:
      deployments: write
      contents: write
      issues: write
      pull-requests: write


    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context))
            let url = "https://os.oxs.cz"
            let deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              production_environment: false,
              environment: "pull-"+context.issue.number,
              transient_environment: true,
              required_contexts: [],
            })
            github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: "success",
              comment: "Yesss",
              log_url: url,
            })
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "Deployed to "+url,
            });
