on:
  pull_request:
    types: [closed]


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions: write-all
    # permissions:
    #   deployments: write
    #   contents: write
    #   issues: write


    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.deleteAnEnvironment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: "pull-"+context.issue.number ,
            });
